TMP: disable gpu profile
karpenter fails to bring up an ubuntu node

karpenter pod log
{"level":"ERROR","time":"2025-03-25T14:26:13.677Z","logger":"controller.nodeclass","message":"discovering amis from ssm, getting ssm parameter \"/aws/service/canonical/ubuntu/eks/20.04/1.32/stable/current/amd64/hvm/ebs-gp2/ami-id\", ParameterNotFound: ","commit":"2c8f2a5","ec2nodeclass":"gpu","query":"/aws/service/canonical/ubuntu/eks/20.04/1.32/stable/current/amd64/hvm/ebs-gp2/ami-id"}

So we tried AL2, and it got farther, the node spins up but the pod fails to start

kubectl describe pod jupyter-asmacdo -n jupyterhub
Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: /usr/local/nvidia/toolkit/nvidia-container-cli.real: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by /usr/local/nvidia/toolkit/libnvidia-container.so.1): unknown